
# Mithril default config file
# You have to edit this before you can use the miner.

# Run `cargo doc --open` and navigate to `mithril::config::MithrilConfig` for up to date documentation

donation = 2.5

[pool]
url = "example.com"
pass = "x"
user = "wallet"

[worker]
threads = 8
auto_tune = { interval_minutes = 15, state_file = "bandit.log" }


[metric]
enabled = true
resolution = 100
sample_interval_seconds = 60
report_file = "mithril_metrics.csv"
